export const sports = [
  "American Football",
  "Aussie Rules Football",
  "Ball Hockey",
  "Baseball",
  "Basketball",
  "Cricket",
  "Field Hockey",
  "Futsal",
  "Gaelic Football",
  "Handball",
  "Hurling",
  "Ice Hockey",
  "Inline Hockey",
  "Lacrosse",
  "Netball",
  "Polo",
  "Rugby",
  "Soccer",
  "Softball",
  "Ultimate Frisbee",
  "Volleyball",
  "Water Polo",
  "Other",
];

export const positions = {
  "American Football": [
    "Quarterback",
    "Running Back",
    "Wide Receiver",
    "Tight End",
    "Offensive Lineman",
    "Defensive Lineman",
    "Linebacker",
    "Cornerback",
    "Safety",
  ],
  "Aussie Rules Football": [
    "Full Forward",
    "Centre Half-Forward",
    "Half-Forward Flank",
    "Forward Pocket",
    "Wing",
    "Centre",
    "Ruck",
    "Ruck-Rover",
    "Rover",
    "Half-Back Flank",
    "Centre Half-Back",
    "Full Back",
  ],
  "Ball Hockey": ["Forward", "Defense", "Goalie"],
  Baseball: [
    "Pitcher",
    "Catcher",
    "First Baseman",
    "Second Baseman",
    "Third Baseman",
    "Shortstop",
    "Left Fielder",
    "Center Fielder",
    "Right Fielder",
  ],
  Basketball: [
    "Point Guard",
    "Shooting Guard",
    "Small Forward",
    "Power Forward",
    "Center",
  ],
  Cricket: ["Batsman", "Bowler", "All-rounder", "Wicket-keeper"],
  "Field Hockey": ["Forward", "Midfielder", "Defender", "Goalkeeper"],
  Futsal: ["Goalkeeper", "Defender", "Winger", "Pivot"],
  "Gaelic Football": [
    "Goalkeeper",
    "Full Back",
    "Half Back",
    "Midfielder",
    "Half Forward",
    "Full Forward",
  ],
  Handball: [
    "Goalkeeper",
    "Left Wing",
    "Left Back",
    "Center Back",
    "Right Back",
    "Right Wing",
    "Pivot",
  ],
  Hurling: [
    "Goalkeeper",
    "Full Back",
    "Half Back",
    "Midfielder",
    "Half Forward",
    "Full Forward",
  ],
  "Ice Hockey": [
    "Center",
    "Left Wing",
    "Right Wing",
    "Defenseman",
    "Goaltender",
  ],
  "Inline Hockey": ["Forward", "Defenseman", "Goalie"],
  Lacrosse: ["Attack", "Midfield", "Defense", "Goalkeeper"],
  Netball: [
    "Goal Shooter",
    "Goal Attack",
    "Wing Attack",
    "Center",
    "Wing Defense",
    "Goal Defense",
    "Goal Keeper",
  ],
  Polo: [
    "Number 1 (Attack)",
    "Number 2 (Midfield)",
    "Number 3 (Defense)",
    "Number 4 (Back)",
  ],
  Rugby: [
    "Prop",
    "Hooker",
    "Lock",
    "Flanker",
    "Number 8",
    "Scrum-half",
    "Fly-half",
    "Center",
    "Wing",
    "Full-back",
  ],
  Soccer: ["Goalkeeper", "Defender", "Midfielder", "Forward"],
  Softball: [
    "Pitcher",
    "Catcher",
    "First Base",
    "Second Base",
    "Third Base",
    "Shortstop",
    "Left Field",
    "Center Field",
    "Right Field",
  ],
  "Ultimate Frisbee": ["Handler", "Cutter"],
  Volleyball: [
    "Outside Hitter",
    "Opposite Hitter",
    "Setter",
    "Middle Blocker",
    "Libero",
  ],
  "Water Polo": [
    "Goalkeeper",
    "Center Forward",
    "Center Back",
    "Wing",
    "Driver",
  ],
  Other: ["Not Specified"],
};
