// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://azmlxacmohiarsaccwhq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6bWx4YWNtb2hpYXJzYWNjd2hxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2MDMwNTQsImV4cCI6MjA1NTE3OTA1NH0.b8nNfeetvEmXIRsfOP7boNtkKmFtQ5hJceOo2a7TgaI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);